version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t public
        environment:
            docker: "true"
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - ./sessions:/var/www/sessions
        links:
            - mysql
    mysql:
        image: mysql:oracle
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: dumko
            MYSQL_PASSWORD: mysqlpw
            MYSQL_DATABASE: Users
            MYSQL_ROOT_PASSWORD: mysqlpw
        volumes:
            - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"